### ISSUE TITLE
Garden linux error on build

### ISSUE THREAD

**Issue by ltagliamonte** [cloudfoundry-incubator/garden-linux#59] opened 2016-02-19 05:01 UTC
Hello,
i would try garden linux containers locally, on ubuntu 14.04, I followed the steps in the main page:
```
git clone --recursive git@github.com:cloudfoundry-incubator/garden-linux-release
cd garden-linux-release
export GOPATH=$PWD
cd $GOPATH/src/github.com/cloudfoundry-incubator/garden-linux # assuming your $GOPATH has only one entry
make
``` 
but on make i got the following error:
```
# github.com/cloudfoundry-incubator/garden-linux/containerizer/system
containerizer/system/namespacing_execer_linux.go:41: cmd.SysProcAttr.UidMappings undefined (type *syscall.SysProcAttr has no field or method UidMappings)
containerizer/system/namespacing_execer_linux.go:42: cmd.SysProcAttr.GidMappings undefined (type *syscall.SysProcAttr has no field or method GidMappings)
containerizer/system/namespacing_execer_linux.go:60: undefined: syscall.SysProcIDMap
containerizer/system/namespacing_execer_linux.go:61: undefined: syscall.SysProcIDMap
make: *** [all] Error 2
```
my go version is:
```
go version go1.2.1 linux/amd64
```
can someone please provide help?

**Comment by goonzoid** [comment] 2016-02-19 09:37
Hi @ltagliamonte,

I suspect the problem is that you're using a rather old version of Go. Garden-Linux is currently tested with Go 1.4.3 (though we may soon move to 1.6), so your best bet is to try 1.4.3. I'll add a note to the documentation about the Go version.

You may also be interested to know that Garden-Linux may be nearing the end of its life, as we're planning to replace it with [Guardian](https://github.com/cloudfoundry-incubator/guardian-release).

I'll close this issue since there's nothing we can do other than update the documentation, but please do reopen it if you still have problems with a more recent version of Go.

**Closed by goonzoid** 2016-02-19 09:37 UTC
