### ISSUE TITLE
incorrect `image:` value in a task definition leads to runaway activity

### ISSUE THREAD

**Issue by redbaron** [cloudfoundry-incubator/garden-linux#54] opened 2015-11-25 16:42 UTC
if step is attempted to run,but has a problem fetching `image:` (lets say it is pointing to a unavailable docker registry like in my  case), then following defects(?) can be seen:
 1. cancelling job from UI first doesn't stop garden-linux spinning in error
 2. stopping garden-linux first doesn't update UI (to be needs checking)
 3. when stopping garden-linux a process like initd -dropCapabilities=false -title="wshd: 6fgavfu0b2v" seems to be "leaked"

**Comment by goonzoid** [comment] 2015-12-07 14:25
Hi @redbaron. Am I right in thinking that this is an issue when using garden-linux with Concourse?

If that's the case, I think 1 and 2 are Concourse bugs. @vito / @xoebus wdyt?

3 is in fact intended behavior. Garden-Linux supports containers continuing to run while the server process is stopped, and can reattach to those containers when started again later, if configured with a snapshot directory.

**Comment by goonzoid** [comment] 2016-03-09 11:22
I'm closing this because it's a concourse issue.

**Closed by goonzoid** 2016-03-09 11:22 UTC
